server:
  port: 1597

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: token-service

  cloud:
    config:
      uri: http://localhost:8888/
      fail-fast: true

jwt:
  secret:
    key: MY_VERY_SECRET_KEY
  valid:
    time: 15811200 #183 days at seconds