server:
  port: 2589

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:

  kafka:
    bootstrap-servers:
      - localhost:8083
      - localhost:8083
      - localhost:8083
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: streaming

  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: postgres
    password: postgres


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none