server:
  port: 1478

spring:

  kafka:
    bootstrap-servers:
      - localhost:8084
      - localhost:8083
      - localhost:8085
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5551/postgres
    username: postgres
    password: postgres
