server:
  port: 1478

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:

  kafka:
    bootstrap-servers:
      - localhost:8083
      - localhost:8083
      - localhost:8083
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: streaming


  data:
    redis:
      host: redis-replica
      port: 6379
      password: my_replica_password

  datasource:
    url: jdbc:postgresql://localhost:5552/postgres
    username: postgres
    password: postgres
