server:
  port: 3698


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: MAIN_SERVER

  data:
    redis:
      host: redis-replica
      port: 6379
      password: my_replica_password

  kafka:
    bootstrap-servers:
      - localhost:8083
      - localhost:8083
      - localhost:8083
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: streaming

  datasource:
    url: jdbc:postgresql://localhost:5551/postgres
    username: postgres
    password: postgres

save-service:
  login: MU_USERNAME
  password: MY_VERY_SECRET_PASSWORD