server:
  port: 3698


eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://eureka:8761/eureka/
=======
      defaultZone: http://eureka:8761/
>>>>>>> 9318f7259e72cb51a789c015369b2bd65256ef07

spring:

  application:
    name: MAIN_SERVER

  data:
    redis:
      host: redis-replica
      port: 6379
      password: my_replica_password

  kafka:
    bootstrap-servers:
      - kafka:8083
      - kafka2:8083
      - kafka3:8083
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: streaming

  datasource:
    url: jdbc:postgresql://patroni1:5432/postgres
    username: postgres
    password: postgres

save-service:
  login: MU_USERNAME
  password: MY_VERY_SECRET_PASSWORD