server:
  port: 3578


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: "REDIS_DATA_SAVE_SERVICE"

  kafka:
    bootstrap-servers:
      - localhost:8083
      - localhost:8083
      - localhost:8083
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: streaming

  data:
    redis:
      host: redis-master
      port: 6379
      password: "my_master_password"