server:
  port: 7896

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:

  security:
    user:
      password: MY_VERY_SECRET_PASSWORD
      name: MU_USERNAME

  application:
    name: "save-service"

  datasource:
    url: jdbc:postgresql://haproxy:5000/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

user:
  password:
    min_length: 6
  name:
    min_length: 5
