server:
  port: 7896

spring:

  security:
    user:
      password: MY_VERY_SECRET_PASSWORD
      name: MU_USERNAME

  application:
    name: "save-service"

  datasource:
    url: jdbc:postgresql://localhost:5553/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

user:
  password:
    min_length: 6
  name:
    min_length: 5
